import Head from 'next/head'
import {Container} from '../../styles/Home'
import styled from 'styled-components';
import Navbar from '../../components/navbar'
import Footer from '../../components/footer'
import Projects from '../../components/projects';





export default function Home() {
  return (
    <Container>
      <Head>
        <title>KPrime21: Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Layout> */}
            <Navbar/>
            <Projects/>    
            <Footer/> 
      {/* </Layout> */}
    </Container>
    
  )
}


