import Head from 'next/head'
import {Container} from '../styles/Home'
import Blogs from '../components/ProjectList'





export default function BlogPage() {
  return (
    <Container>
      <Head>
        <title>KPrime21: Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blogs/>
    </Container>
    
  )
}

