import Head from 'next/head'
import { Container } from '../styles/Home'
import Blogs from '../components/PostList'

let BlogInfo = {
  BlogImage: '/tree.png',
  BlogTitle: 'Playlist Combiner',
  BlogContent: 'This is a app written in Python, using the flask framework \
    to combine your Youtube and Spotify playlist and print it out in a list \
    without having to use the Spotify or Youtube API',
  BlogLink: 'https://github.com/kprime21/playlistcombiner',
}



export default function BlogPage() {
  return (
    <Container>
      <Head>
        <title>KPrime21: Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blogs post={BlogInfo} type='blog' />
    </Container>

  )
}

