import Head from 'next/head'
import { Container } from '../styles/Home'
import Contact from '../components/ContactCard'
import {motion} from 'framer-motion';





export default function ContactPage() {
  return (
    <Container>
      <Head>
        <title>KPrime21: Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      >
      <Contact />
      </motion.div>
    </Container>

  )
}

