import Head from 'next/head'
import { Container } from '../styles/Home'
import Contact from '../components/ContactCard'






export default function ContactPage() {
  return (
    <Container>
      <Head>
        <title>KPrime21: Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Contact />
    </Container>

  )
}

