import Head from 'next/head'
import {Container} from '../styles/Home'
import Projects from '../components/ProjectList'





export default function ProjectsPage() {
  return (
    <Container>
      <Head>
        <title>KPrime21: Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Projects/>
    </Container>
    
  )
}

