import Head from 'next/head'
import { Container } from '../styles/Home'
import Projects from '../components/ProjectList'


let ProjectInfo = {
  ProjectImage: '/tree.png',
  ProjectTitle: 'Playlist Combiner',
  ProjectContent: 'This is a app written in Python, using the flask framework \
    to combine your Youtube and Spotify playlist and print it out in a list \
    without having to use the Spotify or Youtube API',
  ProjectLink: 'https://github.com/kprime21/playlistcombiner',
}


export default function ProjectsPage() {
  return (
    <Container>
      <Head>
        <title>KPrime21: Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Projects propss={ProjectInfo} />
    </Container>

  )
}

