import Head from 'next/head'
import { Container } from '../styles/Home'
import Projects from '../components/PostList'
import { createClient } from '../prismicio'
import {motion} from 'framer-motion'

export async function getStaticProps({ProjectPost}){
  const client = createClient({ProjectPost})

  const page = await (await client.getAllByType('projectpost')).reverse()

  return{
    props: {page},
  }

}


export default function ProjectsPage({page}) {
  return (
    <Container>
      <Head>
        <title>KPrime21: Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      >
      <Projects post={page} type='project' />
      </motion.div>
    </Container>

  )
}

